import { Partner } from "../type/partner";
import { mockServices } from "./mock-services";

export const mockPartners: Partner[] = [
    {
        id: '1',
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
        code: 'PTN001',
        activeDate: '2024-01-15T10:00:00Z',
        name: 'John Smith',
        phoneNumber: '+1234567890',
        rate: 4.8,
        address: '123 Main St, New York, NY',
        sex: 'male',
        age: 32,
        services: [mockServices[0], mockServices[1]],
        status: 'active',
    },
    {
        id: '2',
        image: 'https://randomuser.me/api/portraits/women/2.jpg',
        code: 'PTN002',
        activeDate: '2024-02-20T11:15:00Z',
        name: 'Emily Johnson',
        phoneNumber: '+1234567891',
        rate: 4.6,
        address: '456 Elm St, Los Angeles, CA',
        sex: 'female',
        age: 28,
        services: [mockServices[1], mockServices[2]],
        status: 'active',
    },
    {
        id: '3',
        image: 'https://randomuser.me/api/portraits/men/3.jpg',
        code: 'PTN003',
        activeDate: '2024-03-10T09:30:00Z',
        name: 'Michael Brown',
        phoneNumber: '+1234567892',
        rate: 4.2,
        address: '789 Oak St, Chicago, IL',
        sex: 'male',
        age: 35,
        services: [mockServices[0]],
        status: 'inactive',
    },
    {
        id: '4',
        image: 'https://randomuser.me/api/portraits/women/4.jpg',
        code: 'PTN004',
        activeDate: '2024-01-25T14:45:00Z',
        name: 'Sarah Davis',
        phoneNumber: '+1234567893',
        rate: 4.9,
        address: '321 Pine St, Houston, TX',
        sex: 'female',
        age: 30,
        services: [mockServices[2]],
        status: 'active',
    },
    {
        id: '5',
        image: 'https://randomuser.me/api/portraits/men/5.jpg',
        code: 'PTN005',
        activeDate: '2024-02-05T08:20:00Z',
        name: 'David Wilson',
        phoneNumber: '+1234567894',
        rate: 4.4,
        address: '654 Maple St, Phoenix, AZ',
        sex: 'male',
        age: 29,
        services: [mockServices[0], mockServices[2]],
        status: 'active',
    },
    {
        id: '6',
        image: 'https://randomuser.me/api/portraits/women/6.jpg',
        code: 'PTN006',
        activeDate: '2024-03-15T13:10:00Z',
        name: 'Jessica Miller',
        phoneNumber: '+1234567895',
        rate: 4.7,
        address: '987 Cedar St, Philadelphia, PA',
        sex: 'female',
        age: 26,
        services: [mockServices[1]],
        status: 'active',
    },
    {
        id: '7',
        image: 'https://randomuser.me/api/portraits/men/7.jpg',
        code: 'PTN007',
        activeDate: '2024-01-30T16:00:00Z',
        name: 'Christopher Garcia',
        phoneNumber: '+1234567896',
        rate: 4.1,
        address: '159 Spruce St, San Antonio, TX',
        sex: 'male',
        age: 33,
        services: [mockServices[0], mockServices[1], mockServices[2]],
        status: 'suspended',
    },
    {
        id: '8',
        image: 'https://randomuser.me/api/portraits/women/8.jpg',
        code: 'PTN008',
        activeDate: '2024-02-12T12:25:00Z',
        name: 'Amanda Rodriguez',
        phoneNumber: '+1234567897',
        rate: 4.5,
        address: '753 Birch St, San Diego, CA',
        sex: 'female',
        age: 31,
        services: [mockServices[1], mockServices[2]],
        status: 'active',
    },
    {
        id: '9',
        image: 'https://randomuser.me/api/portraits/men/9.jpg',
        code: 'PTN009',
        activeDate: '2024-03-20T15:40:00Z',
        name: 'Matthew Martinez',
        phoneNumber: '+1234567898',
        rate: 4.3,
        address: '852 Walnut St, Dallas, TX',
        sex: 'male',
        age: 27,
        services: [mockServices[0]],
        status: 'active',
    },
    {
        id: '10',
        image: 'https://randomuser.me/api/portraits/women/10.jpg',
        code: 'PTN010',
        activeDate: '2024-01-08T10:50:00Z',
        name: 'Ashley Anderson',
        phoneNumber: '+1234567899',
        rate: 4.8,
        address: '951 Chestnut St, San Jose, CA',
        sex: 'female',
        age: 29,
        services: [mockServices[2]],
        status: 'active',
    },
    {
        id: '11',
        image: 'https://randomuser.me/api/portraits/men/11.jpg',
        code: 'PTN011',
        activeDate: '2024-02-28T09:10:00Z',
        name: 'Joshua Taylor',
        phoneNumber: '+1234567800',
        rate: 4.0,
        address: '357 Aspen St, Austin, TX',
        sex: 'male',
        age: 34,
        services: [mockServices[0], mockServices[1]],
        status: 'inactive',
    },
    {
        id: '12',
        image: 'https://randomuser.me/api/portraits/women/12.jpg',
        code: 'PTN012',
        activeDate: '2024-03-05T13:35:00Z',
        name: 'Samantha Thomas',
        phoneNumber: '+1234567801',
        rate: 4.6,
        address: '258 Willow St, Jacksonville, FL',
        sex: 'female',
        age: 25,
        services: [mockServices[1]],
        status: 'active',
    },
    {
        id: '13',
        image: 'https://randomuser.me/api/portraits/men/13.jpg',
        code: 'PTN013',
        activeDate: '2024-01-18T11:45:00Z',
        name: 'Andrew Hernandez',
        phoneNumber: '+1234567802',
        rate: 4.4,
        address: '147 Poplar St, Fort Worth, TX',
        sex: 'male',
        age: 30,
        services: [mockServices[0], mockServices[2]],
        status: 'active',
    },
    {
        id: '14',
        image: 'https://randomuser.me/api/portraits/women/14.jpg',
        code: 'PTN014',
        activeDate: '2024-02-22T14:20:00Z',
        name: 'Brittany Moore',
        phoneNumber: '+1234567803',
        rate: 4.7,
        address: '369 Cypress St, Columbus, OH',
        sex: 'female',
        age: 28,
        services: [mockServices[2]],
        status: 'active',
    },
    {
        id: '15',
        image: 'https://randomuser.me/api/portraits/men/15.jpg',
        code: 'PTN015',
        activeDate: '2024-03-12T16:30:00Z',
        name: 'Ryan Jackson',
        phoneNumber: '+1234567804',
        rate: 4.2,
        address: '741 Redwood St, San Francisco, CA',
        sex: 'male',
        age: 31,
        services: [mockServices[0], mockServices[1]],
        status: 'suspended',
    },
    {
        id: '16',
        image: 'https://randomuser.me/api/portraits/women/16.jpg',
        code: 'PTN016',
        activeDate: '2024-01-12T12:40:00Z',
        name: 'Nicole White',
        phoneNumber: '+1234567805',
        rate: 4.9,
        address: '852 Magnolia St, Indianapolis, IN',
        sex: 'female',
        age: 27,
        services: [mockServices[1], mockServices[2]],
        status: 'active',
    },
    {
        id: '17',
        image: 'https://randomuser.me/api/portraits/men/17.jpg',
        code: 'PTN017',
        activeDate: '2024-02-18T09:55:00Z',
        name: 'Kevin Harris',
        phoneNumber: '+1234567806',
        rate: 4.3,
        address: '963 Hickory St, Seattle, WA',
        sex: 'male',
        age: 33,
        services: [mockServices[0]],
        status: 'active',
    },
    {
        id: '18',
        image: 'https://randomuser.me/api/portraits/women/18.jpg',
        code: 'PTN018',
        activeDate: '2024-03-08T15:05:00Z',
        name: 'Rachel Clark',
        phoneNumber: '+1234567807',
        rate: 4.5,
        address: '174 Dogwood St, Denver, CO',
        sex: 'female',
        age: 26,
        services: [mockServices[2]],
        status: 'active',
    },
    {
        id: '19',
        image: 'https://randomuser.me/api/portraits/men/19.jpg',
        code: 'PTN019',
        activeDate: '2024-01-22T11:20:00Z',
        name: 'Daniel Lewis',
        phoneNumber: '+1234567808',
        rate: 4.1,
        address: '285 Palm St, Boston, MA',
        sex: 'male',
        age: 29,
        services: [mockServices[0], mockServices[1], mockServices[2]],
        status: 'inactive',
    },
    {
        id: '20',
        image: 'https://randomuser.me/api/portraits/women/20.jpg',
        code: 'PTN020',
        activeDate: '2024-02-14T13:50:00Z',
        name: 'Lauren Walker',
        phoneNumber: '+1234567809',
        rate: 4.8,
        address: '396 Sycamore St, Nashville, TN',
        sex: 'female',
        age: 32,
        services: [mockServices[1]],
        status: 'active',
    },
];