import { WalletTransaction, WalletSummary } from "@/type/wallet";

export const mockWalletTransactions: WalletTransaction[] = [
    {
        id: "TXN-001",
        type: "expense",
        category: "purchase",
        amount: 15000000,
        description: "Mua máy điều hòa cho phòng họp",
        equipmentName: "Máy điều hòa Daikin FTKC35TVMV",
        equipmentId: "EQ-001",
        date: "2024-12-15T10:30:00Z",
        status: "completed",
        createdBy: "Nguyễn Văn Admin",
        paymentMethod: "bank_transfer",
        reference: "REF-20241215-001",
        notes: "Đã kiểm tra và lắp đặt hoàn tất"
    },
    {
        id: "TXN-002",
        type: "expense",
        category: "maintenance",
        amount: 500000,
        description: "Bảo trì máy in HP LaserJet",
        equipmentName: "Máy in HP LaserJet Pro M404dn",
        equipmentId: "EQ-002",
        date: "2024-12-14T14:15:00Z",
        status: "completed",
        createdBy: "Trần Thị Kỹ Thuật",
        paymentMethod: "cash",
        reference: "REF-20241214-002"
    },
    {
        id: "TXN-003",
        type: "expense",
        category: "repair",
        amount: 1200000,
        description: "Sửa chữa laptop Dell bị hỏng màn hình",
        equipmentName: "Laptop Dell Latitude 5520",
        equipmentId: "EQ-003",
        date: "2024-12-13T09:45:00Z",
        status: "pending",
        createdBy: "Lê Văn IT",
        paymentMethod: "credit_card",
        reference: "REF-20241213-003",
        notes: "Đang chờ linh kiện thay thế"
    },
    {
        id: "TXN-004",
        type: "income",
        category: "rental",
        amount: 2000000,
        description: "Thu tiền cho thuê máy chiếu",
        equipmentName: "Máy chiếu Epson EB-X41",
        equipmentId: "EQ-004",
        date: "2024-12-12T16:20:00Z",
        status: "completed",
        createdBy: "Phạm Thị Kinh Doanh",
        paymentMethod: "bank_transfer",
        reference: "REF-20241212-004"
    },
    {
        id: "TXN-005",
        type: "expense",
        category: "purchase",
        amount: 8500000,
        description: "Mua bộ camera an ninh 8 kênh",
        equipmentName: "Bộ camera Hikvision DS-7208HQHI-K1",
        equipmentId: "EQ-005",
        date: "2024-12-11T11:00:00Z",
        status: "completed",
        createdBy: "Nguyễn Văn Admin",
        paymentMethod: "bank_transfer",
        reference: "REF-20241211-005"
    },
    {
        id: "TXN-006",
        type: "expense",
        category: "maintenance",
        amount: 300000,
        description: "Thay dầu và bảo dưỡng máy phát điện",
        equipmentName: "Máy phát điện Honda EU30is",
        equipmentId: "EQ-006",
        date: "2024-12-10T08:30:00Z",
        status: "completed",
        createdBy: "Hoàng Văn Bảo Trì",
        paymentMethod: "cash",
        reference: "REF-20241210-006"
    },
    {
        id: "TXN-007",
        type: "income",
        category: "rental",
        amount: 1500000,
        description: "Cho thuê thiết bị âm thanh sự kiện",
        equipmentName: "Hệ thống âm thanh JBL PRX815W",
        equipmentId: "EQ-007",
        date: "2024-12-09T19:45:00Z",
        status: "completed",
        createdBy: "Vũ Thị Event",
        paymentMethod: "cash",
        reference: "REF-20241209-007"
    },
    {
        id: "TXN-008",
        type: "expense",
        category: "repair",
        amount: 750000,
        description: "Sửa chữa tủ lạnh bị rò gas",
        equipmentName: "Tủ lạnh Samsung RT38K5032S8",
        equipmentId: "EQ-008",
        date: "2024-12-08T13:20:00Z",
        status: "cancelled",
        createdBy: "Ngô Văn Kỹ Thuật",
        paymentMethod: "bank_transfer",
        reference: "REF-20241208-008",
        notes: "Hủy do không sửa được, sẽ thay mới"
    },
    {
        id: "TXN-009",
        type: "expense",
        category: "purchase",
        amount: 12000000,
        description: "Mua máy tính để bàn cho nhân viên mới",
        equipmentName: "PC Dell OptiPlex 7090 MT",
        equipmentId: "EQ-009",
        date: "2024-12-07T10:15:00Z",
        status: "pending",
        createdBy: "Đỗ Thị HR",
        paymentMethod: "bank_transfer",
        reference: "REF-20241207-009",
        notes: "Đang chờ phê duyệt từ ban giám đốc"
    },
    {
        id: "TXN-010",
        type: "expense",
        category: "maintenance",
        amount: 200000,
        description: "Vệ sinh và bảo trì máy lọc không khí",
        equipmentName: "Máy lọc không khí Xiaomi Mi Air Purifier 3H",
        equipmentId: "EQ-010",
        date: "2024-12-06T15:50:00Z",
        status: "completed",
        createdBy: "Lý Văn Vệ Sinh",
        paymentMethod: "cash",
        reference: "REF-20241206-010"
    }
];

export const mockWalletSummary: WalletSummary = {
    totalIncome: 3500000,
    totalExpense: 38950000,
    balance: -35450000,
    transactionCount: 10
};
