import { Review } from "@/type/review";

export const mockReviews: Review[] = [
    {
        id: '1',
        user: {
            id: 'u1',
            name: 'Alice Nguyen',
            image: 'https://randomuser.me/api/portraits/women/1.jpg',
            phone: '+84111111111',
        },
        partner: {
            id: 'p1',
            name: 'SkyHome Cleaning',
            image: 'https://randomuser.me/api/portraits/men/11.jpg',
            phone: '+84123456789',
        },
        orderId: 'o1',
        rating: 5,
        comment: 'Excellent service, highly recommended!',
        status: 'responded',
        createdAt: '2024-06-01T10:00:00Z',
        updatedAt: '2024-06-01T10:00:00Z',
    },
    {
        id: '2',
        user: {
            id: 'u2',
            name: 'Bob Tran',
            image: 'https://randomuser.me/api/portraits/men/2.jpg',
            phone: '+84222222222',
        },
        partner: {
            id: 'p2',
            name: 'GreenHome Services',
            image: 'https://randomuser.me/api/portraits/men/12.jpg',
            phone: '+84987654321',
        },
        orderId: 'o2',
        rating: 4,
        comment: 'Very good experience overall.',
        status: 'viewed',
        createdAt: '2024-06-02T12:30:00Z',
        updatedAt: '2024-06-02T12:30:00Z',
    },
    {
        id: '3',
        user: {
            id: 'u3',
            name: 'Charlie Le',
            image: 'https://randomuser.me/api/portraits/men/3.jpg',
            phone: '+84333333333',
        },
        partner: {
            id: 'p1',
            name: 'SkyHome Cleaning',
            image: 'https://randomuser.me/api/portraits/men/11.jpg',
            phone: '+84123456789',
        },
        orderId: 'o3',
        rating: 3,
        comment: 'Average, could be better.',
        status: 'received',
        createdAt: '2024-06-03T09:15:00Z',
        updatedAt: '2024-06-03T09:15:00Z',
    },
    {
        id: '4',
        user: {
            id: 'u4',
            name: 'Diana Pham',
            image: 'https://randomuser.me/api/portraits/women/4.jpg',
            phone: '+84444444444',
        },
        partner: {
            id: 'p3',
            name: 'CleanPro Team',
            image: 'https://randomuser.me/api/portraits/men/13.jpg',
            phone: '+84888888888',
        },
        orderId: 'o4',
        rating: 2,
        comment: 'Not satisfied with the service.',
        status: 'responded',
        createdAt: '2024-06-04T14:45:00Z',
        updatedAt: '2024-06-04T14:45:00Z',
    },
    {
        id: '5',
        user: {
            id: 'u5',
            name: 'Eve Hoang',
            image: 'https://randomuser.me/api/portraits/women/5.jpg',
            phone: '+84555555555',
        },
        partner: {
            id: 'p2',
            name: 'GreenHome Services',
            image: 'https://randomuser.me/api/portraits/men/12.jpg',
            phone: '+84987654321',
        },
        orderId: 'o5',
        rating: 5,
        comment: 'Outstanding! Will use again.',
        status: 'viewed',
        createdAt: '2024-06-05T16:20:00Z',
        updatedAt: '2024-06-05T16:20:00Z',
    },
    {
        id: '6',
        user: {
            id: 'u6',
            name: 'Frank Vu',
            image: 'https://randomuser.me/api/portraits/men/6.jpg',
            phone: '+84666666666',
        },
        partner: {
            id: 'p1',
            name: 'SkyHome Cleaning',
            image: 'https://randomuser.me/api/portraits/men/11.jpg',
            phone: '+84123456789',
        },
        orderId: 'o6',
        rating: 4,
        comment: 'Quick response and friendly staff.',
        status: 'received',
        createdAt: '2024-06-06T11:10:00Z',
        updatedAt: '2024-06-06T11:10:00Z',
    },
    {
        id: '7',
        user: {
            id: 'u7',
            name: 'Grace Nguyen',
            image: 'https://randomuser.me/api/portraits/women/7.jpg',
            phone: '+84777777777',
        },
        partner: {
            id: 'p3',
            name: 'CleanPro Team',
            image: 'https://randomuser.me/api/portraits/men/13.jpg',
            phone: '+84888888888',
        },
        orderId: 'o7',
        rating: 3,
        comment: 'Service was okay, nothing special.',
        status: 'responded',
        createdAt: '2024-06-07T13:25:00Z',
        updatedAt: '2024-06-07T13:25:00Z',
    },
    {
        id: '8',
        user: {
            id: 'u8',
            name: 'Henry Dao',
            image: 'https://randomuser.me/api/portraits/men/8.jpg',
            phone: '+84888888888',
        },
        partner: {
            id: 'p2',
            name: 'GreenHome Services',
            image: 'https://randomuser.me/api/portraits/men/12.jpg',
            phone: '+84987654321',
        },
        orderId: 'o8',
        rating: 1,
        comment: 'Very disappointed, would not recommend.',
        status: 'viewed',
        createdAt: '2024-06-08T15:40:00Z',
        updatedAt: '2024-06-08T15:40:00Z',
    },
    {
        id: '9',
        user: {
            id: 'u9',
            name: 'Ivy Tran',
            image: 'https://randomuser.me/api/portraits/women/9.jpg',
            phone: '+84999999999',
        },
        partner: {
            id: 'p1',
            name: 'SkyHome Cleaning',
            image: 'https://randomuser.me/api/portraits/men/11.jpg',
            phone: '+84123456789',
        },
        orderId: 'o9',
        rating: 5,
        comment: 'Amazing experience from start to finish.',
        status: 'received',
        createdAt: '2024-06-09T17:55:00Z',
        updatedAt: '2024-06-09T17:55:00Z',
    },
    {
        id: '10',
        user: {
            id: 'u10',
            name: 'Jacky Phan',
            image: 'https://randomuser.me/api/portraits/men/10.jpg',
            phone: '+84101010101',
        },
        partner: {
            id: 'p3',
            name: 'CleanPro Team',
            image: 'https://randomuser.me/api/portraits/men/13.jpg',
            phone: '+84888888888',
        },
        orderId: 'o10',
        rating: 2,
        comment: 'Could improve communication.',
        status: 'received',
        createdAt: '2024-06-10T19:05:00Z',
        updatedAt: '2024-06-10T19:05:00Z',
    },
];
