import { FavoritePartner } from "../type/favorite-partner";


export const mockFavoritePartners: FavoritePartner[] = [
    {
        id: '1',
        userId: 'u1',
        name: 'Alice Nguyen',
        sex: 'female',
        age: 28,
        rate: 4.5,
        like: true,
    },

    {
        id: '3',
        userId: 'u3',
        name: 'Cathy Le',
        sex: 'female',
        age: 25,
        rate: 4.8,
        like: true,
    },
    {
        id: '5',
        userId: 'u5',
        name: 'Emma Vo',
        sex: 'female',
        age: 27,
        rate: 4.7,
        like: true,
    },
    {
        id: '7',
        userId: 'u7',
        name: 'Grace Bui',
        sex: 'female',
        age: 29,
        rate: 4.6,
        like: true,
    },
    {
        id: '8',
        userId: 'u8',
        name: 'Henry Dang',
        sex: 'male',
        age: 31,
        rate: 4.3,
        like: false,
    },
    {
        id: '9',
        userId: 'u9',
        name: 'Ivy Do',
        sex: 'female',
        age: 26,
        rate: 4.9,
        like: true,
    },
    {
        id: '10',
        userId: 'u10',
        name: 'Jackie Lam',
        sex: 'male',
        age: 33,
        rate: 4.0,
        like: false,
    },
    {
        id: '11',
        userId: 'u11',
        name: 'Kim Ly',
        sex: 'female',
        age: 24,
        rate: 4.4,
        like: true,
    },
    {
        id: '12',
        userId: 'u12',
        name: 'Leo Vu',
        sex: 'male',
        age: 29,
        rate: 4.2,
        like: false,
    },
    {
        id: '13',
        userId: 'u13',
        name: 'Mia Chau',
        sex: 'female',
        age: 27,
        rate: 4.7,
        like: true,
    },
    {
        id: '14',
        userId: 'u14',
        name: 'Nathan Quang',
        sex: 'male',
        age: 34,
        rate: 3.8,
        like: false,
    },
    {
        id: '15',
        userId: 'u15',
        name: 'Olivia Phan',
        sex: 'female',
        age: 28,
        rate: 4.5,
        like: true,
    },
    {
        id: '16',
        userId: 'u16',
        name: 'Peter Nguyen',
        sex: 'male',
        age: 32,
        rate: 4.1,
        like: false,
    },
    {
        id: '17',
        userId: 'u17',
        name: 'Quinn Tran',
        sex: 'female',
        age: 25,
        rate: 4.8,
        like: true,
    },
    {
        id: '18',
        userId: 'u18',
        name: 'Ryan Le',
        sex: 'male',
        age: 30,
        rate: 4.0,
        like: false,
    },
    {
        id: '19',
        userId: 'u19',
        name: 'Sophie Vo',
        sex: 'female',
        age: 26,
        rate: 4.9,
        like: true,
    },
    {
        id: '20',
        userId: 'u20',
        name: 'Tommy Ho',
        sex: 'male',
        age: 31,
        rate: 4.3,
        like: false,
    },
];