import { User } from "../type/user";

export const mockUsers: User[] = [
    {
        id: '1',
        customerName: 'Nguyễn Văn A',
        customerCode: 'KH001',
        age: 28,
        gender: 'Male',
        referralCode: 'GT123',
        phoneNumber: '0901234567',
        dateOfBirth: '1996-01-15',
        cardHolderName: 'Nguyễn Văn A',
        bankName: 'Vietcombank',
        bankAccountNumber: '0123456789',
        address: '123 Đường Lê Lợi, Quận 1, TP.HCM',
        createdAt: '2025-07-01',
        image: 'https://randomuser.me/api/portraits/men/1.jpg',
        rank: 0,
    },
    {
        id: '2',
        customerName: 'Trần Thị B',
        customerCode: 'KH002',
        age: 32,
        gender: 'Female',
        referralCode: 'GT456',
        phoneNumber: '0912345678',
        dateOfBirth: '1992-03-22',
        cardHolderName: 'Trần Thị B',
        bankName: 'Techcombank',
        bankAccountNumber: '9876543210',
        address: '456 Đường Nguyễn Huệ, Quận 1, TP.HCM',
        createdAt: '2025-07-02',
        image: 'https://randomuser.me/api/portraits/women/2.jpg',
        rank: 1,
    },
    {
        id: '3',
        customerName: 'Lê Văn C',
        customerCode: 'KH003',
        age: 25,
        gender: 'Male',
        referralCode: 'GT789',
        phoneNumber: '0923456789',
        dateOfBirth: '1999-07-10',
        cardHolderName: 'Lê Văn C',
        bankName: 'ACB',
        bankAccountNumber: '1234567890',
        address: '789 Đường Trần Hưng Đạo, Quận 5, TP.HCM',
        createdAt: '2025-07-03',
        image: 'https://randomuser.me/api/portraits/men/3.jpg',
        rank: 2,
    },
    {
        id: '4',
        customerName: 'Phạm Thị D',
        customerCode: 'KH004',
        age: 29,
        gender: 'Female',
        referralCode: 'GT321',
        phoneNumber: '0934567890',
        dateOfBirth: '1995-11-05',
        cardHolderName: 'Phạm Thị D',
        bankName: 'BIDV',
        bankAccountNumber: '2345678901',
        address: '321 Đường Cách Mạng Tháng 8, Quận 10, TP.HCM',
        createdAt: '2025-07-04',
        image: 'https://randomuser.me/api/portraits/women/4.jpg',
        rank: 3,
    },
    {
        id: '5',
        customerName: 'Hoàng Văn E',
        customerCode: 'KH005',
        age: 30,
        gender: 'Other',
        referralCode: 'GT654',
        phoneNumber: '0945678901',
        dateOfBirth: '1994-05-20',
        cardHolderName: 'Hoàng Văn E',
        bankName: 'Sacombank',
        bankAccountNumber: '3456789012',
        address: '654 Đường Điện Biên Phủ, Quận Bình Thạnh, TP.HCM',
        createdAt: '2025-07-05',
        image: 'https://randomuser.me/api/portraits/men/5.jpg',
        rank: 4,
    }
];
