import { Transaction } from "@/type/transaction";


export const mockTransactions: Transaction[] = [
    {
        _id: '1',
        orderId: 'ORD-1001',
        subtotal: 150,
        promotionAmount: 10,
        promotionName: 'SUMMER10',
        amount: 140,
        paymentMethod: 'Credit Card',
        paymentStatus: 'success',
        vatAmount: 14,
        vatRate: 0.1,
        createdAt: '2024-06-01T10:15:00Z',
        orderType: 'online',
        orderStatus: 'completed',
        orderAddress: '123 Main St, NY',
        userId: 'u001',
        userFullName: 'Alice Johnson',
        userPhone: '555-0101'
    },
    {
        _id: '2',
        orderId: 'ORD-2002',
        subtotal: 75.5,
        promotionAmount: 5.5,
        promotionName: 'REFUND5',
        amount: 70,
        paymentMethod: 'PayPal',
        paymentStatus: 'refund',
        vatAmount: 7,
        vatRate: 0.1,
        createdAt: '2024-06-02T11:20:00Z',
        orderType: 'online',
        orderStatus: 'refunded',
        orderAddress: '456 Oak Ave, LA',
        userId: 'u002',
        userFullName: 'Bob Smith',
        userPhone: '555-0102'
    },
    {
        _id: '3',
        orderId: 'ORD-3003',
        subtotal: 29.99,
        promotionAmount: 0,
        promotionName: '',
        amount: 29.99,
        paymentMethod: 'Bank Transfer',
        paymentStatus: 'success',
        vatAmount: 3,
        vatRate: 0.1,
        createdAt: '2024-06-03T09:05:00Z',
        orderType: 'subscription',
        orderStatus: 'active',
        orderAddress: '789 Pine Rd, SF',
        userId: 'u003',
        userFullName: 'Carol Lee',
        userPhone: '555-0103'
    },
    {
        _id: '4',
        orderId: 'ORD-1002',
        subtotal: 200,
        promotionAmount: 20,
        promotionName: 'WELCOME20',
        amount: 180,
        paymentMethod: 'Credit Card',
        paymentStatus: 'success',
        vatAmount: 18,
        vatRate: 0.1,
        createdAt: '2024-06-04T14:30:00Z',
        orderType: 'online',
        orderStatus: 'completed',
        orderAddress: '321 Maple St, TX',
        userId: 'u004',
        userFullName: 'David Kim',
        userPhone: '555-0104'
    },
    {
        _id: '5',
        orderId: 'ORD-2003',
        subtotal: 50,
        promotionAmount: 0,
        promotionName: '',
        amount: 50,
        paymentMethod: 'PayPal',
        paymentStatus: 'refund',
        vatAmount: 5,
        vatRate: 0.1,
        createdAt: '2024-06-05T16:45:00Z',
        orderType: 'online',
        orderStatus: 'refunded',
        orderAddress: '654 Cedar Ave, FL',
        userId: 'u005',
        userFullName: 'Eva Green',
        userPhone: '555-0105'
    }
    // ...add more as needed
];
